name: Build Storybook
on:
  workflow_call:
    inputs:
      pr-number:
        required: false
        type: string
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: ".nvmrc"
      - name: Install Node Packages
        run: npm ci
      - name: Lint SCSS
        run: npm run lint

  Format-Check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: ".nvmrc"
      - name: Install Node Packages
        run: npm ci
      - name: Check formatting
        run: npm run format:check

  Build-Storybook-Assets:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: ".nvmrc"
      - name: Install Node Packages
        run: npm ci
      - name: Build Storybook Assets
        run: npm run build:storybook
        env:
          NODE_OPTIONS: "--max_old_space_size=8192"
      - name: Add .nojekyll file to allow for node_modules to be included in bundle
        run: touch _site/.nojekyll
      - name: Archive Storybook Assets
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: storybook-assets
          path: _site
          retention-days: 1
